# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-k8s
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: chaimaboussaidi2000/docker-spring
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongo:27017/mydatabase" # Utilisez le nom du service MongoDB pour la connexion

---

apiVersion: v1
kind: Service
metadata:
  name: springboot-k8ssvc
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: "TCP"
      port: 9090
      targetPort: 9090
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: "TCP"
      port: 27017
      targetPort: 27017
